AntEnv_v3:
    joints: 8
    timesteps: 100
    latent_size: 100
    layer_sizes: [800, 700, 600, 500, 400, 300, 200, 100]
    condition_size: 0
    epochs: 1000
    reward: 100.0
    reward_tol: 10.0